### ISSUE TITLE
backend-16.01.0-pre8 with Fedora 22

### ISSUE THREAD

**Issue by mailonator** [Studio-Link-v2/backend#2]
I've compiled backend-16.01.0-pre8 from source (I need a 32bit version due to reasons).
It starts up:

$ studio-link-standalone 
baresip v0.4.17 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address: IPv4=wlan0:192.168.28.83
aucodec: opus/48000/2
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: alsa
auplay: alsa
medianat: stun
medianat: turn
medianat: ice
Studio Link Webapp v16.01.0-dev - Standalone Copyright (C) 2016 Sebastian Reimers <studio-link.de>
aufilt: webapp_vumeter
http listening on port: 38760
using stunserver: 'stun:50b5acb0:7818c13ff749b2@stun.studio-link.de'
50b5acb0@studio-link.de: Using medianat `ice'
dl: mod: ./menu.so (./menu.so: cannot open shared object file: No such file or directory)
module menu.so: No such file or directory
dl: mod: ./vidloop.so (./vidloop.so: cannot open shared object file: No such file or directory)
module vidloop.so: No such file or directory
Populated 3 audio codecs
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
UNREGISTERING: sip:50b5acb0@studio-link.de
DELETE USER sip:50b5acb0@studio-link.de
using stunserver: 'stun:50b5acb0:7818c13ff749b2@stun.studio-link.de'
50b5acb0@studio-link.de: Using medianat `ice'
50b5acb0@studio-link.de: {0/TLS/v4} 200 OK (kamailio (4.2.7 (x86_64/linux))) [1 binding]
Register OK: sip:50b5acb0@studio-link.de
Vector smash protection is enabled.
*************************
A coding exception was thrown and uncaught in a Task.

Full message: TypeError: this.Paths is null
Full stack: Agent.wipe@resource:///modules/sessionstore/SessionWorker.js:296:7
worker.dispatch@resource:///modules/sessionstore/SessionWorker.js:21:24
anonymous/AbstractWorker.prototype.handleMessage@resource://gre/modules/workers/PromiseWorker.js:122:16
@resource:///modules/sessionstore/SessionWorker.js:30:41

The web pages comes up. But the option button is do-nothing.
And can you tell me how to select audio input (I've an USB mic) and output?

Maybe it is relevant that I've pulseaudio running.

Thanks and Greetings, 
Frank Elsner

**Comment by sreimers** [comment]
Thanks for testing!

> The web pages comes up. But the option button is do-nothing.

You can ignore the option button in the dev standalone version at the moment.

> And can you tell me how to select audio input (I've an USB mic) and output?

Pulseaudio should be no problem. The linux standalone app use the default system device you set in pulseaudio (alsa:default).

**Comment by sreimers** [comment]
> A coding exception was thrown and uncaught in a Task.
> 
> Full message: TypeError: this.Paths is null
> Full stack: Agent.wipe@resource:///modules/sessionstore/SessionWorker.js:296:7
> worker.dispatch@resource:///modules/sessionstore/SessionWorker.js:21:24
> anonymous/AbstractWorker.prototype.handleMessage@resource://gre/modules/workers/PromiseWorker.js:122:16
> @resource:///modules/sessionstore/SessionWorker.js:30:41

That must be browser warnings/errors. Normaly nothing related to baresip or studio-link.

**Comment by mailonator** [comment]
On Fri, 29 Jan 2016 08:59:58 -0800 Sebastian Reimers wrote:
> Thanks for testing!
> 
> > The web pages comes up. But the option button is do-nothing.
> 
> You can ignore the option button in the dev standalone version at the moment.
> 
> > And can you tell me how to select audio input (I've an USB mic) and output?
> 
> Pulseaudio should be no problem. The linux standalone app use the default system device you set in pulseaudio (alsa:default).

Thanks for your quick response. I'll do further testing during the weekend.

BTW, I'm a beginner, not far away from start :-)


Nice Weekend, Frank

**Comment by mailonator** [comment]
On Fri, 29 Jan 2016 18:29:12 +0100 Frank Elsner wrote:

  [ ... ]

> Thanks for your quick response. I'll do further testing during the weekend.

Could not wait. Too curious :-)

IT WORKS!

Thanks, Frank

**Comment by sreimers** [comment]
Perfect. Have a nice weekend too!
