### ISSUE TITLE
Pegelanzeigen im Webinterface ...

### ISSUE THREAD

**Issue by mailonator** [Studio-Link-v2/backend#3]

**Comment by saschaludwig** [comment]
auf? zu? auf? zu? ;-)

**Comment by mailonator** [comment]
On Wed, 27 Apr 2016 13:35:38 -0700 Sascha Ludwig wrote:
> auf? zu? auf? zu? ;-)

Leider. Mangels Erfahrung mit Issues in github. Sorry.

--Frank

**Comment by saschaludwig** [comment]
Halb so wild glaube ich, jeder fängt ja mal an :-)
