### ISSUE TITLE
Die Pegelanzeigen im WebInterface ..

### ISSUE THREAD

**Issue by mailonator** [Studio-Link-v2/backend#4]
... scheinen mir vertauscht. Ich erwarte als Incoming das Signal von außen und Outgoing das Signal, das rausgeht. Scheint aber andersrum. Kannste mal draufschauen oder meine Erwartungen korrigieren?

Gruß, Frank

**Comment by saschaludwig** [comment]
Aus Plugin Sicht ist das incoming das Signal welches das Plugin von der Soundkarte/DAW erhält, und das Outgoing das Signal welches zur Soundkarte geschickt wird und dann aus dem Audio-Port kommt. Allerdings ist beim klassischen MusicTaxi ist TX das was man 'raus sendet' und RX was man von der Gegenstelle empfängt. Also genau andersrum. https://rc5.de/screenshots/Screenshot_20160427_224501.png

**Comment by sreimers** [comment]
Hi Sascha und Frank,

richtig, ich glaube es macht Sinn das noch einmal zu tauschen. Danke für das Feedback!
