### ISSUE TITLE
DNS SRV and NAPTR records on studio-link.de

### ISSUE THREAD

**Issue by mkuron** [Studio-Link-v2/backend#6]
This issue is not strictly related to the backend, but I couldn't find any other place to report it.

The DNS records on studio-link.de appear to be incorrect and do not permit calling a Studio-Link account with a 3rd party client by placing a direct call to `sip:abcdefgh@studio-link.de`; it only reliably works with `sip:abcdefgh@studio-link.de;transport=tls`. The official client software is not affected because it explicitly specifies `transport=tls`.

```
$ host -t NAPTR studio-link.de
studio-link.de has NAPTR record 0 0 "s" "SIPS+D2T" "" _sips._tcp.studio-link.de.
studio-link.de has NAPTR record 0 0 "s" "SIP+D2T" "" _sip._tcp.studio-link.de.
$ host -t SRV _sips._tcp.studio-link.de
_sips._tcp.studio-link.de has SRV record 0 10 443 sip.studio-link.de.
$ host -t SRV _sip._tcp.studio-link.de
_sip._tcp.studio-link.de has SRV record 0 10 5061 sip.studio-link.de.
$ host -t SRV _sip._udp.studio-link.de
_sip._udp.studio-link.de has no SRV record
```

First of all, the two NAPTR records should have different priorities (that is the first `0`). The one for `SIPS` should have a lower number, e.g. `10`, and the one for `SIP` a higher number, e.g. `20`, to make clients prefer the encrypted connection.
Secondly, the server does not actually accept TCP connections on port 5061. As far as I can tell, it only accepts TLS connections on port 443. Therefore, only the `SIPS` records should even be present in DNS.

**Comment by sreimers** [comment]
Thanks! DNS is fixed now, 5061 was also TLS but promoted as unencrypted.

**Comment by mkuron** [comment]
That was quick. Thanks for fixing it; it's working fine now using the Blink SIP client.

With a Snom VoIP phone however, I'm experiencing a problem with the TLS certificate:
```
Jun 11 10:49:32.259 [ERROR ] TLS: Error 62 at depth 0: Hostname mismatch
Jun 11 10:49:32.260 [ERROR ] TLS: Cert s: /OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.studio-link.de
Jun 11 10:49:32.260 [ERROR ] TLS: Cert i: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
Jun 11 10:49:32.277 [ERROR ] TLS: X509v3 extensions: X509v3 Authority Key Identifier: keyid:90:AF:6A:3A:94:5A:0B:D8:90:EA:12:56:73:DF:43:B4:3A:28:DA:E7 X509v3 Subject Key Identifier: 24:CB:6A:91:EA:52:8A:51:28:F3:97:F5:14:2B:99:EB:7C:66:70:2E X509v3 Key Usage: critical Digital Signature, Key Encipherment X509v3 Basic Constraints: critical CA:FALSE X509v3 Extended Key Usage: TLS Web Server Authentication, TLS Web Client Authentication X509v3 Certificate Policies: Policy: 1.3.6.1.4.1.6449.1.2.2.7 CPS: https://secure.comodo.com/CPS Policy: 2.23.140.1.2.1 X509v3 CRL Distribution Points: Full Name: URI:http://crl.comodoca.com/COMODORSADomainValidationSecureServerCA.crl Authority Information Access: CA Issuers - URI:http://crt.comodoca.com/COMODORSADomainValidationSecureServerCA.crt OCSP - URI:http://ocsp.comodoca.com X509v3 Subject Alternative Name: DNS:*.studio-link.de, DNS:studio-link.de Signature Algorithm: sha256WithRSAEncryption 5b:3d:ce:b3:7f:8a:31:5d:23:16:91:e0:58:5b:0c:81:fb:f3: 81:e5:82:e9:ad:bd:5a:51:b0:3b:01:d6:f5:fb:82:6d:c7:43: fa:52:7b:19:c2:f3:9f:9b:e8:5c:6f:0e:1e:f0:fc:12:71:fb: d4:68:2e:4d:52:e7:58:13:68:f5:a8:40:d9:d5:d3:a4:f9:ef: 88:c3:4b:60:0c:b2:5e:b7:eb:70:59:d2:e1:14:62:e9:bd:14: 74:70:c9:ca:68:0d:d3:35:d8:89:20:38:39:37:8c:0d:91:73: e3:e0:fd:9e:09:73:c3:47:95:30:c7:81:b7:69:6b:0f:20:8e: c2:1c:83:f3:91:d0:1c:5c:92:51:75:3b:25:52:54:16:72:61: 19:a2:a2:62:a1:cc:62:64:d0:e4:70:39:73:b3:db:a8:54:f1: 0e:15:c4:71:5f:1d:39:af:a9:c2:39:6f:20:e4:e4:3b:b7:4a: 79:c8:74:46:14:6f:9d:aa:71:67:f3:33:dd:8a:07:d1:06:69: d3:4d:1d:f4:22:21:f2:52:13:0c:73:83:e5:a6:fe:fc:4a:46: eb:d4:2e:aa:15:c4:b5:e5:d5:c9:01:a0:8b:14:ad:fc:2b:60: 20:e4:85:96:8a:59:2a:61:ec:89:7a:5b:76:c9:1c:5b:1e:94: 30:4a:43:f5
Jun 11 10:49:32.281 [ERROR ] PHN: TPL: Socket Error: 415/35/connected, Tls error, closing
```
Per RFC 5922, wildcards are supposed to be ignored for SIP connections, but the certificate has a subject alternative name for _studio-link.de_, which should be sufficient here. I am suspecting the phone also looks for a subject alternative name for _sip.studio-link.de_. That is probably in-line with the RFC, which seems to require a subject alternative name entry for both the domain name (_studio-link.de_) which has the SRV record and the server name (_sip.studio-link.de_) pointed to by the SRV record.
I was able to enable wildcard certificates on the phone by setting the hidden setting [host_name_validation_flags](http://wiki.snom.com/Settings/host_name_validation_flags) to value 8, but the problem should be fixed server-side by adding _sip.studio-link.de_ to the certificate's subject alternative names.

**Comment by sreimers** [comment]
Have you experience with Let’s Encrypt certificates and SIP clients, are they widely trusted?

**Comment by mkuron** [comment]
Software SIP clients typically use the trust store from the operating system, so I would expect them to support Let's Encrypt via their IdenTrust cross-signature. Snom phones with recent firmware support Let's Encrypt directly. Most other physical phones probably also ship with a more or less extensive list of CA certificates in their firmware. IdenTrust is big enough and common enough that their CA certificate should be included almost everywhere. Just make sure that your server sends the entire chain, including the Let's Encrypt intermediate CAs.

I think it would be fine to switch to Let's Encrypt. There may be some devices that contain the COMODO root CA but not IdenTrust, but there might also be devices where it is vice versa. The worst case scenario is that some people might need to manually upload the Let's Encrypt CA certificate to their phone.
