### ISSUE TITLE
patch failed, compilation failed (Fedora 23)

### ISSUE THREAD

**Issue by mailonator** [Studio-Link-v2/backend#7]
Aktuelles Fedora 23 (alle Updates drin). Compilation von backend-16.04.1-beta hat auf identischem
System am 2.7. einwandfrei geklappt und heute das 

[frank@pangea backend-16.04.1-beta]$ export TRAVIS_OS_NAME="linux"; build/build.sh
 ...
+ cd baresip-master
+ curl https://github.com/Studio-Link-v2/baresip/compare/Studio-Link-v2:master...studio-link-config.patch
+ patch -p1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7330    0  7330    0     0   8463      0 --:--:-- --:--:-- --:--:--  8464
patching file src/conf.c
Hunk #1 FAILED at 167.
1 out of 1 hunk FAILED -- saving rejects to file src/conf.c.rej
patching file src/config.c
Hunk #1 FAILED at 312.
Hunk #2 succeeded at 416 with fuzz 2 (offset 29 lines).
Hunk #3 succeeded at 429 with fuzz 1 (offset 34 lines).
Hunk #4 succeeded at 463 (offset 35 lines).
Hunk #5 succeeded at 590 (offset 35 lines).
Hunk #6 succeeded at 604 with fuzz 1 (offset 36 lines).
Hunk #7 succeeded at 693 (offset 36 lines).
Hunk #8 succeeded at 717 (offset 36 lines).
Hunk #9 FAILED at 701.
Hunk #10 succeeded at 746 (offset 32 lines).
2 out of 10 hunks FAILED -- saving rejects to file src/config.c.rej
[frank@pangea backend-16.04.1-beta]$

**Comment by sreimers** [comment]
Das liegt vermutlich daran, das der Patch zweimal angewendet wird.
Probier mal das "src" Verzeichnis vor dem Build zu löschen.

**Comment by sreimers** [comment]
Kommando zurück, ich sehe gerade den Fehler. Fixe ich morgen, ich habe schon Baresip aktualisiert, daher passt der Patch nicht mehr.

**Comment by mailonator** [comment]
"morgen" ist ja schon 'ne Weile her :-) Gibt's 'n neuen Zeitrahmen?

**Comment by sreimers** [comment]
Axo sollte mittlerweile gefixt sein. Du müsstest aber die Sourcen neu auschecken.

**Comment by mailonator** [comment]
Ok, keine Probleme mehr. Danke.
