### ISSUE TITLE
plugin crashes ardour 5

### ISSUE THREAD

**Issue by unDocUMeantIt** [Studio-Link-v2/backend#8]
i've tried using the plugin (dowlnoaded today) with ardour 5 (5.3.4-1kxstudio2) on (k)ubuntu 16.04. shortly after adding the plugin to the bus, ardour crashes. it fires up the web browser, that remais open with a closed websocket.

**Comment by sreimers** [comment]
Can you test this version:

https://github.com/Studio-Link-v2/backend/releases/download/v16.04.1-beta/studio-link-plugin-linux-fix-sslv2.zip

**Comment by unDocUMeantIt** [comment]
yes, this fixes the crash!

is there documentation on how to properly use all of the nice knobs somewhere?
