### ISSUE TITLE
StudioLink.component instantly crashes Logic when added to a track

### ISSUE THREAD

**Issue by vivalamovie** [Studio-Link-v2/backend#9]
macOS Sierra 10.12.2 on a Mac mini 6,1 (Late 2012), fresh installed OS (still wet), Logic Pro X 10.2.4, StudioLink.component 16.12.0 (showing up with auval, output below, also survives Logic startup plugin check)

1. opening new Logic Project with Audio Track
2. adding StudioLink to Track: Audio 1
3. very long beachball (without much CPU usage)
4. crash (log attached [crash.txt](https://github.com/Studio-Link-v2/backend/files/664898/crash.txt))

What else can I do to help with this problem?

```
aufx Ypss ITSR  -  ITSR: StudioLink
activate baresip v0.5.0 Copyright (C) 2010 - 2015 Alfred E. Heggestad et al.
activate baresip v0.5.0 Copyright (C) 2010 - 2015 Alfred E. Heggestad et al.
Local network address:  IPv4=en0:192.168.178.39  IPv6=utun1:fde5:546f:edaa:5dfd:9032:ca52:bcef:c7bf
aucodec: opus/48000/2
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: effect
auplay: effect
medianat: stun
medianat: turn
medianat: ice
Studio Link Webapp v16.12.0-beta - Effect Plugin Copyright (C) 2016 Sebastian Reimers <studio-link.de>
http listening on port: 52996
Populated 3 audio codecs
Populated 0 audio filters
Populated 0 video codecs
Populated 0 video filters
auto mix enabled
DESTRUCT SESSION
ua: stop all (forced=0)
webapp_ws_close
```

**Comment by sreimers** [comment]
Thanks for reporting. The crash report shows that the main thread (com.apple.music.apps.MAAudioUnitSupport) dies. So the plug-in is triggering something in Logic.
The debugging is difficult, normaly I would need a Logic version localy to do a step by step debugging, but 200 Euro invest with the possibility to find another show-stopper (routing, recording etc.) and the time is difficult at the moment. My current advice is to use Reaper/Ultraschall (maybe only for recording) and export so you can edit the files in Logic.

**Comment by vivalamovie** [comment]
Ok, thank you for that honest response. If you get to the point where testing with Logic gets interesting, don't hesitate to contact me.
